// @ts-nocheck
// biome-ignore-all lint: This file is autogenerated
// This file is autogenerated by src/scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  "text-reveal": {
    name: "text-reveal",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/text-reveal.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/text-reveal.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "grid-particles": {
    name: "grid-particles",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/grid-particles.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/grid-particles.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  flow: {
    name: "flow",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/flow.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/flow.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  cutout: {
    name: "cutout",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/cutout.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/cutout.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "cyber-button": {
    name: "cyber-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["cutout"],
    files: [
      {
        path: "src/registry/default/ui/cyber-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/cyber-button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "decrypted-text": {
    name: "decrypted-text",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/decrypted-text.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/decrypted-text.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-reveal-example": {
    name: "text-reveal-example",
    description: "",
    type: "registry:component",
    registryDependencies: ["text-reveal"],
    files: [
      {
        path: "src/registry/default/example/text-reveal-example.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/text-reveal-example.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "grid-particles-example": {
    name: "grid-particles-example",
    description: "",
    type: "registry:component",
    registryDependencies: ["grid-particles"],
    files: [
      {
        path: "src/registry/default/example/grid-particles-example.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/grid-particles-example.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "circuits-example": {
    name: "circuits-example",
    description: "",
    type: "registry:component",
    registryDependencies: ["circuits"],
    files: [
      {
        path: "src/registry/default/example/circuits-example.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/circuits-example.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "flow-example": {
    name: "flow-example",
    description: "",
    type: "registry:ui",
    registryDependencies: ["flow", "cutout"],
    files: [
      {
        path: "src/registry/default/example/flow-example.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/flow-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "cyber-button-example": {
    name: "cyber-button-example",
    description: "",
    type: "registry:ui",
    registryDependencies: ["cyber-button"],
    files: [
      {
        path: "src/registry/default/example/cyber-button-example.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/cyber-button-example.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "decrypted-text-example": {
    name: "decrypted-text-example",
    description: "",
    type: "registry:ui",
    registryDependencies: ["decrypted-text"],
    files: [
      {
        path: "src/registry/default/example/decrypted-text-example.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/decrypted-text-example.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
