// @ts-nocheck
// biome-ignore-all lint: This file is autogenerated
// This file is autogenerated by src/scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  "text-reveal": {
    name: "text-reveal",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/text-reveal.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/text-reveal.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "grid-particles": {
    name: "grid-particles",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/grid-particles.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/grid-particles.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  stream: {
    name: "stream",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/default/ui/stream.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/stream.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-reveal-example": {
    name: "text-reveal-example",
    description: "",
    type: "registry:component",
    registryDependencies: ["text-reveal"],
    files: [
      {
        path: "src/registry/default/example/text-reveal-example.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/text-reveal-example.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "grid-particles-example": {
    name: "grid-particles-example",
    description: "",
    type: "registry:component",
    registryDependencies: ["grid-particles"],
    files: [
      {
        path: "src/registry/default/example/grid-particles-example.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/default/example/grid-particles-example.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "stream-example": {
    name: "stream-example",
    description: "",
    type: "registry:component",
    registryDependencies: ["stream"],
    files: [
      {
        path: "src/registry/default/example/stream-example.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/stream-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
